title: Chrysanthi Doxa # your name (or website title) here
logo: "https://github.com/ChDoxa/Portfolio-Chrysa-Doxa/blob/master/images/profile2.jpg?raw=true" # your photo (or logo) here
description: >description your text below (remove <br> elements if you don't need line breaks)
 <strong>Msc Geophysicist</strong>
  <strong>GIS Analyst</strong>
  <strong>Data Scientist enthusiastic</strong>
  <br><br>
  <a>Curriculum Vitae</a>
  <a href="https://www.linkedin.com/in/chrysa-doxa-8709381b0/">LinkedIn Profile</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
