title: Chrysanthi Doxa # your name (or website title) here
logo: "https://github.com/ChDoxa/Portfolio-Chrysa-Doxa/blob/master/images/profile2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Msc Geophysicist 
  <br><br>
  GIS Analyst 
  <br><br>
  Data Scientist enthusiastic 
  <br><br>
  <aCurriculum Vitae</a>
  <a href="https://www.linkedin.com/in/chrysa-doxa-8709381b0/">LinkedIn Profile</a> 
